spring.application.name=backend

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/threadbare
spring.datasource.username=admin
spring.datasource.password=secret

# JPA / Hibernate Schema Management
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.open-in-view=false 